package modelo;
// Generated 30/05/2016 09:56:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Asesoria generated by hbm2java
 */
public class Asesoria  implements java.io.Serializable {


     private int idAsesoria;
     private Alumno alumno;
     private Materia materia;
     private Tutor tutor;
     private int costo;
     private Date fecAsesoria;
     private String direccion;
     private String comentario;
     private Integer calificacionAlumno;
     private Integer calificacionTutor;
     private char estado;

    public Asesoria() {
    }

	
    public Asesoria(int idAsesoria, Alumno alumno, Materia materia, Tutor tutor, int costo, Date fecAsesoria, String direccion, char estado) {
        this.idAsesoria = idAsesoria;
        this.alumno = alumno;
        this.materia = materia;
        this.tutor = tutor;
        this.costo = costo;
        this.fecAsesoria = fecAsesoria;
        this.direccion = direccion;
        this.estado = estado;
    }
    public Asesoria(int idAsesoria, Alumno alumno, Materia materia, Tutor tutor, int costo, Date fecAsesoria, String direccion, String comentario, Integer calificacionAlumno, Integer calificacionTutor, char estado) {
       this.idAsesoria = idAsesoria;
       this.alumno = alumno;
       this.materia = materia;
       this.tutor = tutor;
       this.costo = costo;
       this.fecAsesoria = fecAsesoria;
       this.direccion = direccion;
       this.comentario = comentario;
       this.calificacionAlumno = calificacionAlumno;
       this.calificacionTutor = calificacionTutor;
       this.estado = estado;
    }
   
    public int getIdAsesoria() {
        return this.idAsesoria;
    }
    
    public void setIdAsesoria(int idAsesoria) {
        this.idAsesoria = idAsesoria;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Tutor getTutor() {
        return this.tutor;
    }
    
    public void setTutor(Tutor tutor) {
        this.tutor = tutor;
    }
    public int getCosto() {
        return this.costo;
    }
    
    public void setCosto(int costo) {
        this.costo = costo;
    }
    public Date getFecAsesoria() {
        return this.fecAsesoria;
    }
    
    public void setFecAsesoria(Date fecAsesoria) {
        this.fecAsesoria = fecAsesoria;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Integer getCalificacionAlumno() {
        return this.calificacionAlumno;
    }
    
    public void setCalificacionAlumno(Integer calificacionAlumno) {
        this.calificacionAlumno = calificacionAlumno;
    }
    public Integer getCalificacionTutor() {
        return this.calificacionTutor;
    }
    
    public void setCalificacionTutor(Integer calificacionTutor) {
        this.calificacionTutor = calificacionTutor;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


