package modelo;
// Generated 30/05/2016 09:56:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private int idMateria;
     private String nombreMateria;
     private int areaMateria;
     private Set tutorMaterias = new HashSet(0);
     private Set asesorias = new HashSet(0);

    public Materia() {
    }

	
    public Materia(int idMateria, String nombreMateria, int areaMateria) {
        this.idMateria = idMateria;
        this.nombreMateria = nombreMateria;
        this.areaMateria = areaMateria;
    }
    public Materia(int idMateria, String nombreMateria, int areaMateria, Set tutorMaterias, Set asesorias) {
       this.idMateria = idMateria;
       this.nombreMateria = nombreMateria;
       this.areaMateria = areaMateria;
       this.tutorMaterias = tutorMaterias;
       this.asesorias = asesorias;
    }
   
    public int getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(int idMateria) {
        this.idMateria = idMateria;
    }
    public String getNombreMateria() {
        return this.nombreMateria;
    }
    
    public void setNombreMateria(String nombreMateria) {
        this.nombreMateria = nombreMateria;
    }
    public int getAreaMateria() {
        return this.areaMateria;
    }
    
    public void setAreaMateria(int areaMateria) {
        this.areaMateria = areaMateria;
    }
    public Set getTutorMaterias() {
        return this.tutorMaterias;
    }
    
    public void setTutorMaterias(Set tutorMaterias) {
        this.tutorMaterias = tutorMaterias;
    }
    public Set getAsesorias() {
        return this.asesorias;
    }
    
    public void setAsesorias(Set asesorias) {
        this.asesorias = asesorias;
    }




}


