package modelo;
// Generated 19/05/2016 12:03:59 AM by Hibernate Tools 4.3.1



/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private int idSolicitud;
     private Alumno alumno;
     private Asesoria asesoria;
     private Materia materia;
     private Tutor tutor;
     private char estado;

    public Solicitud() {
    }

    public Solicitud(int idSolicitud, Alumno alumno, Asesoria asesoria, Materia materia, Tutor tutor, char estado) {
       this.idSolicitud = idSolicitud;
       this.alumno = alumno;
       this.asesoria = asesoria;
       this.materia = materia;
       this.tutor = tutor;
       this.estado = estado;
    }
   
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Asesoria getAsesoria() {
        return this.asesoria;
    }
    
    public void setAsesoria(Asesoria asesoria) {
        this.asesoria = asesoria;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Tutor getTutor() {
        return this.tutor;
    }
    
    public void setTutor(Tutor tutor) {
        this.tutor = tutor;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


