package modelo;
// Generated 26/05/2016 04:28:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tutor generated by hbm2java
 */
public class Tutor  implements java.io.Serializable {


     private int idUsuario;
     private Usuario usuario;
     private String nivelEstudio;
     private Set asesorias = new HashSet(0);
     private Set tutorMaterias = new HashSet(0);

    public Tutor() {
    }

	
    public Tutor(Usuario usuario) {
        this.usuario = usuario;
    }
    public Tutor(Usuario usuario, String nivelEstudio, Set asesorias, Set tutorMaterias) {
       this.usuario = usuario;
       this.nivelEstudio = nivelEstudio;
       this.asesorias = asesorias;
       this.tutorMaterias = tutorMaterias;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNivelEstudio() {
        return this.nivelEstudio;
    }
    
    public void setNivelEstudio(String nivelEstudio) {
        this.nivelEstudio = nivelEstudio;
    }
    public Set getAsesorias() {
        return this.asesorias;
    }
    
    public void setAsesorias(Set asesorias) {
        this.asesorias = asesorias;
    }
    public Set getTutorMaterias() {
        return this.tutorMaterias;
    }
    
    public void setTutorMaterias(Set tutorMaterias) {
        this.tutorMaterias = tutorMaterias;
    }




}


