package modelo;
// Generated 19/05/2016 12:03:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tutor generated by hbm2java
 */
public class Tutor  implements java.io.Serializable {


     private int idUsuario;
     private Usuario usuario;
     private String nivelEstudio;
     private Set solicituds = new HashSet(0);
     private Set tutorMaterias = new HashSet(0);

    public Tutor() {
    }

	
    public Tutor(Usuario usuario) {
        this.usuario = usuario;
    }
    public Tutor(Usuario usuario, String nivelEstudio, Set solicituds, Set tutorMaterias) {
       this.usuario = usuario;
       this.nivelEstudio = nivelEstudio;
       this.solicituds = solicituds;
       this.tutorMaterias = tutorMaterias;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNivelEstudio() {
        return this.nivelEstudio;
    }
    
    public void setNivelEstudio(String nivelEstudio) {
        this.nivelEstudio = nivelEstudio;
    }
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }
    public Set getTutorMaterias() {
        return this.tutorMaterias;
    }
    
    public void setTutorMaterias(Set tutorMaterias) {
        this.tutorMaterias = tutorMaterias;
    }




}


