package modelo;
// Generated 26/05/2016 04:28:37 PM by Hibernate Tools 4.3.1



/**
 * TutorMateria generated by hbm2java
 */
public class TutorMateria  implements java.io.Serializable {


     private TutorMateriaId id;
     private Materia materia;
     private Tutor tutor;

    public TutorMateria() {
    }

    public TutorMateria(TutorMateriaId id, Materia materia, Tutor tutor) {
       this.id = id;
       this.materia = materia;
       this.tutor = tutor;
    }
   
    public TutorMateriaId getId() {
        return this.id;
    }
    
    public void setId(TutorMateriaId id) {
        this.id = id;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Tutor getTutor() {
        return this.tutor;
    }
    
    public void setTutor(Tutor tutor) {
        this.tutor = tutor;
    }




}


